package service

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"ai-japanese-learning/internal/model"
)

type TranslationService struct {
	aiService *AIService
}

func NewTranslationService(aiService *AIService) *TranslationService {
	return &TranslationService{aiService: aiService}
}

type translationResult struct {
	JapaneseContent string `json:"japanese_content"`
	SourceType      string `json:"source_type"`
	IsAIGenerated   bool   `json:"is_ai_generated"`
	Note            string `json:"note"`
}

func (s *TranslationService) TranslateToJapanese(ctx context.Context, language, content string, level model.JLPTLevel) (string, string, bool, string) {
	cleaned := strings.TrimSpace(content)
	if language == "ja" {
		return cleaned, "user_uploaded", false, "Japanese article detected. Stored without translation."
	}

	const (
		taskType      = "article_translation"
		fallbackModel = "placeholder-translation-service"
		promptVersion = aiPromptVersionV12
	)
	modelName := fallbackModel
	if s.aiService != nil {
		modelName = s.aiService.ModelNameFor(ctx, fallbackModel)
	}
	prompt := promptArticleTranslation(language, cleaned, level)
	request := map[string]any{
		"language":   language,
		"content":    cleaned,
		"jlpt_level": string(level),
		"prompt":     prompt,
	}
	if s.aiService != nil {
		inputHash := s.aiService.HashInput(language + ":" + string(level) + ":" + cleaned)
		cacheKey := s.aiService.CacheKey(taskType, inputHash, modelName, promptVersion)
		if cached, ok, err := s.aiService.GetCached(ctx, cacheKey); err == nil && ok {
			var result translationResult
			if err := json.Unmarshal([]byte(cached.ResponseJSON), &result); err == nil && strings.TrimSpace(result.JapaneseContent) != "" {
				return result.JapaneseContent, result.SourceType, result.IsAIGenerated, result.Note
			}
		}

		result, err := s.translateWithAI(ctx, prompt)
		if err != nil {
			s.aiService.LogFailure(ctx, taskType, request, err, modelName, promptVersion)
			result = buildPlaceholderTranslation(language, cleaned, level)
		}
		if _, err := s.aiService.StoreCached(ctx, taskType, inputHash, cacheKey, request, result, modelName, promptVersion); err != nil {
			s.aiService.LogFailure(ctx, taskType, request, err, modelName, promptVersion)
		}
		return result.JapaneseContent, result.SourceType, result.IsAIGenerated, result.Note
	}

	result := buildPlaceholderTranslation(language, cleaned, level)
	return result.JapaneseContent, result.SourceType, result.IsAIGenerated, result.Note
}

func (s *TranslationService) translateWithAI(ctx context.Context, prompt AIPrompt) (translationResult, error) {
	if !s.aiService.ProviderAvailableFor(ctx) {
		return translationResult{}, fmt.Errorf("ai provider unavailable")
	}
	raw, err := s.aiService.CompleteJSON(ctx, prompt)
	if err != nil {
		return translationResult{}, err
	}
	var result translationResult
	if err := json.Unmarshal([]byte(raw), &result); err != nil {
		return translationResult{}, fmt.Errorf("parse ai translation: %w", err)
	}
	if strings.TrimSpace(result.JapaneseContent) == "" {
		return translationResult{}, fmt.Errorf("ai translation missing japanese_content")
	}
	if strings.TrimSpace(result.SourceType) == "" {
		result.SourceType = "ai_translated"
	}
	result.IsAIGenerated = true
	if strings.TrimSpace(result.Note) == "" {
		result.Note = "Generated by configured AI provider."
	}
	return result, nil
}

func buildPlaceholderTranslation(language, cleaned string, level model.JLPTLevel) translationResult {
	translated := fmt.Sprintf(
		"これは %s 向けに整えた日本語版の記事です。\n\n原文要約:\n%s",
		level,
		cleaned,
	)
	return translationResult{
		JapaneseContent: translated,
		SourceType:      "ai_translated",
		IsAIGenerated:   true,
		Note:            "Using placeholder translation service with AI cache in v0.8-review. Replace with real AI provider in later versions.",
	}
}
